"""Typer CLI entry point for smart-git."""

from __future__ import annotations

from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.panel import Panel
from rich.syntax import Syntax

from smart_git_cli.ai_engine import generate_commit_message, generate_release_notes
from smart_git_cli.errors import SmartGitError
from smart_git_cli.git_engine import GitEngine

app = typer.Typer(
    invoke_without_command=True,
    help="AI assistant for Conventional Commits and release notes.",
)
console = Console()
err_console = Console(stderr=True)

VERSION = "0.1.0"


def _fail(exc: Exception) -> None:
    err_console.print(f"[bold red][ERROR][/bold red] {exc}", highlight=False)
    raise typer.Exit(code=1)


@app.callback()
def main(
    ctx: typer.Context,
    version: bool = typer.Option(False, "--version", help="Show version and exit."),
) -> None:
    if version:
        console.print(f"smart-git v{VERSION}")
        raise typer.Exit()
    if ctx.invoked_subcommand is None:
        console.print(ctx.get_help())
        raise typer.Exit()


@app.command()
def commit(
    all: bool = typer.Option(
        False, "-a", "--all", help="Stage all changes before committing."
    ),
) -> None:
    """Generate a Conventional Commit message and commit staged changes."""
    try:
        engine = GitEngine.from_dir()
        if all:
            engine.repo.git.add(A=True)
        diff = engine.diff_text()
    except SmartGitError as exc:
        _fail(exc)

    console.print("[dim]Analyzing your diff...[/dim]")
    try:
        message = generate_commit_message(engine.truncate(diff))
    except SmartGitError as exc:
        _fail(exc)

    console.print(
        Panel(
            Syntax(message, "text", theme="monokai", word_wrap=True),
            title="[bold yellow]Suggested commit message[/bold yellow]",
            border_style="yellow",
        )
    )

    if not typer.confirm("Proceed with this commit?", default=True):
        console.print("[yellow]Commit cancelled.[/yellow]")
        raise typer.Exit()

    try:
        engine.repo.index.commit(message)
    except Exception as exc:
        _fail(exc)

    console.print("[green]Commit created successfully![/green]")


@app.command()
def release(
    output: Path = typer.Option(
        Path("CHANGELOG.md"), "--output", "-o", help="Path for the generated changelog."
    ),
    limit: int = typer.Option(100, "--limit", help="Max commits to include."),
) -> None:
    """Generate release notes and write them to a CHANGELOG.md file."""
    try:
        engine = GitEngine.from_dir()
        commits = engine.commits_since_tag(limit=limit)
    except SmartGitError as exc:
        _fail(exc)

    console.print("[dim]Generating release notes...[/dim]")
    try:
        notes = generate_release_notes(commits)
    except SmartGitError as exc:
        _fail(exc)

    header = "> Automatically generated by smart-git.\n\n"
    output.write_text("# Changelog\n\n" + header + notes, encoding="utf-8")
    console.print(f"[green]Release notes written to {output}[/green]")
    console.print(Syntax(notes, "markdown", theme="dark", word_wrap=True))


if __name__ == "__main__":
    app()